version: "3"

services:
  nginx:
    # 配置docker容器日志文件
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    image: nginx
    container_name: hw-nginx
    ports:
      - "80:80"
      - "443:443"
    privileged: true #是否让docker 应用容器 获取宿主机root权限（特殊权限）
    restart: always #失败重启
    volumes:
      - /home/heart-words/nginx/html:/nginx/html
      - /home/heart-words/nginx/ssl:/etc/nginx/ssl
      - /home/heart-words/nginx/logs:/var/log/nginx
      - /home/heart-words/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - redis
      - mysql8
      - app

  mysql8:
    # 配置docker容器日志文件
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    container_name: hw-mysql
    image: mysql:8
    restart: always
    privileged: true #是否让docker 应用容器 获取宿主机root权限（特殊权限）
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=YT0864
      - TZ=Asia/Shanghai
    volumes:
      - /home/heart-words/mysql/data:/var/lib/mysql
      - /home/heart-words/mysql/files:/var/lib/mysql-files
    ports:
      - 3306:3306

  redis:
    # 配置docker容器日志文件
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    image: redis
    container_name: hw-redis
    privileged: true #是否让docker 应用容器 获取宿主机root权限（特殊权限）
    ports:
      - 6379:6379
    restart: always
    volumes:
      - /home/heart-words/redis/data:/data
      - /home/heart-words/redis/redis.conf:/usr/local/etc/redis/redis.conf

  app:
    # 配置docker容器日志文件
    logging:
      driver: "json-file"
      options:
        max-size: "1000m"
        max-file: "3"
    build:
      context: ./
      dockerfile: Dockerfile
    image: hw-app
    container_name: hw-app
    privileged: true
    mem_limit: 1000m
    # MaxRAMPercentage=80.0:设置jvm使用容器最大内存(mem_limit)的80%
    entrypoint: [
        "java",
        "-server",
        "-XX:+UnlockExperimentalVMOptions",
        "-XX:+UseCGroupMemoryLimitForHeap",
        "-XX:MaxRAMPercentage=80.0",
        "-XX:+HeapDumpOnOutOfMemoryError",
        "-XX:HeapDumpPath=/logs/HeapDump",
        "-jar",
        "/app.jar"
    ]
    command: mkdir /logs && mkdir /logs/HeapDump
    ports:
      - 30000:30000
    restart: always
    volumes:
      - /home/heart-words/app/logs:/logs
    depends_on:
      - redis
      - mysql8

